# print("Know thyself" , "\n\n" , "Bahtiyor\n" 'print("____________________________________")')
# print("____________________________________")
# print("Know thyself\n"*10)
# print("  *")
# print(" ***")
# print("*****")
# print("  *")
# print("  *")
# print(" ***")
print("  ^")
print(" / \\")
print("/   \\")
print('-----')
print("  |  ")
print("  |  ")
print(" ... ")

print("When 10 is divided by 3, it is" ,10//3, "and the reminder" , 10%3)